name: autodoc
#triggers
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master # THIS IS IMPORTANT
    - uses: actions/setup-python@v2 # THIS IS IMPORTANT
      with:
        python-version: '3.9'
    - name: dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: venv
      run: python -m venv venv && source venv/bin/activate && pip install -r requirements.txt
    - name: documentation
      run: cd docs && source ../venv/bin/activate && python ../venv/bin/sphinx-apidoc -f -d 8 -o . .. && make html && cd ..
    - name: publish
      run: |
        git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
        git branch -D gh-pages
        git checkout gh-pages
        git pull --rebase
        git checkout master
        mkdocs build --clean
        mkdocs gh-deploy --config-file docs/mkdocs.yml --force
